server:
  port: ${services.clouddriver.port:7002}
  address: 0.0.0.0

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

default:
  account:
    env: ${providers.kubernetes.primaryCredentials.name}

kubernetes:
  enabled: true
  accounts:
    - name: kube-aws-SpinnakerTest-cluster
      dockerRegistries: 
        - accountName: docker-hub 

dockerRegistry:
  enabled: true
  accounts:
    - name: docker-hub
      address: https://hub.docker.com
	  username: cdongsi
	  password: TODO
      repositories:
        - library/nginx

credentials:
  primaryAccountTypes: ${providers.kubernetes.primaryCredentials.name}
  challengeDestructiveActionsEnvironments: ${providers.kubernetes.primaryCredentials.name}
